import { ensureDatabase, getSession, json } from '../../../db/runtime';
type GuestInput = { name: string; type: string; host?: string; note?: string; allocation?: number };
export async function GET(request: Request) { const session = await getSession(request); if (!session) return json({ error: 'Sign in required' }, 401); const db = await ensureDatabase(); const [event, guests, activity] = await Promise.all([db.prepare('SELECT * FROM event_state WHERE id = 1').first(), db.prepare('SELECT id, name, guest_type AS type, host, note, allocation, checked_in AS checked FROM guests ORDER BY id DESC').all(), db.prepare('SELECT action, detail, role_key AS role, created_at AS createdAt FROM activity ORDER BY id DESC LIMIT 12').all()]); return json({ event, guests: guests.results, activity: activity.results, session }); }
export async function POST(request: Request) { const session = await getSession(request); if (!session) return json({ error: 'Sign in required' }, 401); const body = await request.json() as { action?: string; id?: number; amount?: number; direction?: 'in' | 'out'; guests?: GuestInput[]; replace?: boolean }; const db = await ensureDatabase(); const now = new Date().toISOString();
  if (body.action === 'check') { if (!session.permissions.includes('check')) return json({ error: 'Not allowed' }, 403); const guest = await db.prepare('SELECT name, allocation, checked_in FROM guests WHERE id = ?').bind(body.id).first<{ name: string; allocation: number; checked_in: number }>(); if (!guest) return json({ error: 'Guest not found' }, 404); const checked = Math.min(guest.allocation, guest.checked_in + Math.max(1, body.amount ?? 1)); await db.batch([db.prepare('UPDATE guests SET checked_in = ?, updated_at = ? WHERE id = ?').bind(checked, now, body.id), db.prepare('INSERT INTO activity (action, detail, role_key, created_at) VALUES (?, ?, ?, ?)').bind('check-in', `${guest.name}: ${checked}/${guest.allocation}`, session.role, now)]); return json({ checked }); }
  if (body.action === 'counter') { if (!session.permissions.includes('counter')) return json({ error: 'Not allowed' }, 403); const direction = body.direction === 'out' ? 'out' : 'in'; const statement = direction === 'in' ? 'UPDATE event_state SET inside = inside + 1, updated_at = ? WHERE id = 1' : 'UPDATE event_state SET inside = MAX(0, inside - 1), out_count = out_count + 1, updated_at = ? WHERE id = 1'; await db.batch([db.prepare(statement).bind(now), db.prepare('INSERT INTO activity (action, detail, role_key, created_at) VALUES (?, ?, ?, ?)').bind('counter', direction, session.role, now)]); return json({ event: await db.prepare('SELECT * FROM event_state WHERE id = 1').first() }); }
  if (body.action === 'import') { if (!session.permissions.includes('import')) return json({ error: 'Not allowed' }, 403); const incoming = (body.guests ?? []).slice(0, 5000); if (!incoming.length) return json({ error: 'No guests found in that file' }, 400); const queries = []; if (body.replace) queries.push(db.prepare('DELETE FROM guests')); for (const guest of incoming) { const allocation = Math.max(1, Math.min(50, Number(guest.allocation) || 1)); queries.push(db.prepare('INSERT INTO guests (name, normalized_name, guest_type, host, note, allocation, checked_in, created_at, updated_at) VALUES (?, ?, ?, ?, ?, ?, 0, ?, ?)').bind(guest.name.trim(), guest.name.toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g, ''), guest.type, guest.host || 'PDA', guest.note || null, allocation, now, now)); } queries.push(db.prepare('INSERT INTO activity (action, detail, role_key, created_at) VALUES (?, ?, ?, ?)').bind('import', `${incoming.length} guests`, session.role, now)); await db.batch(queries); return json({ imported: incoming.length }); }
  return json({ error: 'Unknown action' }, 400);
}
